import java.io.IOException;
import javax.swing.JOptionPane;
/**
 *
 * @author Matheus
 */
public class RunMVM {
    private short mem[];
    private int enderecoDeCarga;
    private int lastPosition = 0;
    
    public void Inicializa(){
        mem = new short[1024];
        enderecoDeCarga = 0;
    }
    
    public void Run() throws IOException{
        int programa = Integer.parseInt(JOptionPane.showInputDialog("Escolha um Programa: "));
        //Botao.main(args, mem);
        //int enderecoDeCarga = 0;

        switch (programa) {
            case 1: //Exemplo 1 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)19);
                atribuirMemoria(2, (short)19);
                atribuirMemoria(3, (short)40);
                break;
            case 2: //Exemplo 2 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)44);
                atribuirMemoria(2, (short)3);
                atribuirMemoria(3, (short)19);
                atribuirMemoria(4, (short)9);
                atribuirMemoria(5, (short)2);
                atribuirMemoria(6, (short)40);
                break;
            case 3: //Exemplo 3 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)3);
                atribuirMemoria(2, (short)29);
                atribuirMemoria(3, (short)20);
                atribuirMemoria(4, (short)20);
                atribuirMemoria(5, (short)22);
                atribuirMemoria(6, (short)25);
                atribuirMemoria(7, (short)10);
                atribuirMemoria(8, (short)26);
                atribuirMemoria(9, (short)3);
                atribuirMemoria(10, (short)40);
                break;
            case 4: //Exemplo 4 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)19);
                atribuirMemoria(2, (short)19);
                atribuirMemoria(3, (short)9);
                atribuirMemoria(4, (short)12);
                atribuirMemoria(5, (short)19);
                atribuirMemoria(6, (short)19);
                atribuirMemoria(7, (short)3);
                atribuirMemoria(8, (short)5);
                atribuirMemoria(9, (short)12);
                atribuirMemoria(10, (short)40);
                break;
            case 5: //Exemplo 5 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)3);
                atribuirMemoria(2, (short)29);
                atribuirMemoria(3, (short)20);
                atribuirMemoria(4, (short)20);
                atribuirMemoria(5, (short)22);
                atribuirMemoria(6, (short)25);
                atribuirMemoria(7, (short)10);
                atribuirMemoria(8, (short)26);
                atribuirMemoria(9, (short)3);
                atribuirMemoria(10, (short)20);
                atribuirMemoria(11, (short)20);
                atribuirMemoria(12, (short)22);
                atribuirMemoria(13, (short)25);
                atribuirMemoria(14, (short)10);
                atribuirMemoria(15, (short)26);
                atribuirMemoria(16, (short)3);
                atribuirMemoria(17, (short)20);
                atribuirMemoria(18, (short)20);
                atribuirMemoria(19, (short)22);
                atribuirMemoria(20, (short)25);
                atribuirMemoria(21, (short)10);
                atribuirMemoria(22, (short)40);
                break;
            case 6: //Exemplo 6 - OK!
                atribuirMemoria(0, (short)0);
                atribuirMemoria(1, (short)44);
                atribuirMemoria(2, (short)255);
                atribuirMemoria(3, (short)48);
                atribuirMemoria(4, (short)27);
                atribuirMemoria(5, (short)30);
                atribuirMemoria(6, (short)30);
                atribuirMemoria(7, (short)27);
                atribuirMemoria(8, (short)60);
                atribuirMemoria(9, (short)30);
                atribuirMemoria(10, (short)40);
                atribuirMemoria(30, (short)31);
                atribuirMemoria(31, (short)44);
                atribuirMemoria(32, (short)30);
                atribuirMemoria(33, (short)9);
                atribuirMemoria(34, (short)8);
                atribuirMemoria(35, (short)30);
                atribuirMemoria(36, (short)38);
                atribuirMemoria(37, (short)28);
                atribuirMemoria(60, (short)31);
                atribuirMemoria(61, (short)5);
                atribuirMemoria(62, (short)255);
                atribuirMemoria(63, (short)3);
                atribuirMemoria(64, (short)30);
                atribuirMemoria(65, (short)38);
                atribuirMemoria(66, (short)28);
                break;
            case 7: //Exemplo 1 - Lista - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)18);
                atribuirMemoria(10, (short)0);
                atribuirMemoria(11, (short)9);
                atribuirMemoria(12, (short)2);
                atribuirMemoria(13, (short)9);
                atribuirMemoria(14, (short)3);
                atribuirMemoria(15, (short)28);
                atribuirMemoria(18, (short)0);
                atribuirMemoria(19, (short)44);
                atribuirMemoria(20, (short)9);
                atribuirMemoria(21, (short)48);
                atribuirMemoria(22, (short)27);
                atribuirMemoria(23, (short)10);
                atribuirMemoria(24, (short)27);
                atribuirMemoria(25, (short)10);
                atribuirMemoria(26, (short)40);
                break;
            case 8: //Exemplo 2 - Lista - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)18);
                atribuirMemoria(10, (short)19);
                atribuirMemoria(11, (short)9);
                atribuirMemoria(12, (short)2);
                atribuirMemoria(13, (short)9);
                atribuirMemoria(14, (short)3);
                atribuirMemoria(15, (short)28);
                atribuirMemoria(18, (short)0);
                atribuirMemoria(19, (short)44);
                atribuirMemoria(20, (short)9);
                atribuirMemoria(21, (short)48);
                atribuirMemoria(22, (short)27);
                atribuirMemoria(23, (short)10);
                atribuirMemoria(24, (short)27);
                atribuirMemoria(25, (short)10);
                atribuirMemoria(26, (short)40);
                break;
            case 9: //Exemplo 3 - Lista - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)18);
                atribuirMemoria(8, (short)34);
                atribuirMemoria(9, (short)11);
                atribuirMemoria(10, (short)8);
                atribuirMemoria(11, (short)3);
                atribuirMemoria(12, (short)19);
                atribuirMemoria(13, (short)19);
                atribuirMemoria(14, (short)43);
                atribuirMemoria(15, (short)3);
                atribuirMemoria(16, (short)35);
                atribuirMemoria(17, (short)28);
                atribuirMemoria(18, (short)44);
                atribuirMemoria(19, (short)7);
                atribuirMemoria(20, (short)48);
                atribuirMemoria(21, (short)0);
                atribuirMemoria(22, (short)31);
                atribuirMemoria(23, (short)27);
                atribuirMemoria(24, (short)8);
                atribuirMemoria(25, (short)31);
                atribuirMemoria(26, (short)27);
                atribuirMemoria(27, (short)8);
                atribuirMemoria(28, (short)40);
                break;
            case 10: //Exemplo 4 - Lista - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)18);
                atribuirMemoria(8, (short)34);
                atribuirMemoria(9, (short)11);
                atribuirMemoria(10, (short)8);
                atribuirMemoria(11, (short)3);
                atribuirMemoria(12, (short)19);
                atribuirMemoria(13, (short)19);
                atribuirMemoria(14, (short)43);
                atribuirMemoria(15, (short)3);
                atribuirMemoria(16, (short)35);
                atribuirMemoria(17, (short)28);
                atribuirMemoria(18, (short)44);
                atribuirMemoria(19, (short)7);
                atribuirMemoria(20, (short)48);
                atribuirMemoria(21, (short)0);
                atribuirMemoria(22, (short)31);
                atribuirMemoria(23, (short)27);
                atribuirMemoria(24, (short)8);
                atribuirMemoria(25, (short)38);
                atribuirMemoria(26, (short)31);
                atribuirMemoria(27, (short)27);
                atribuirMemoria(28, (short)8);
                atribuirMemoria(29, (short)38);
                atribuirMemoria(30, (short)40);
                break;
            case 11: //Exemplo Device Driver - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)35);
                atribuirMemoria(2, (short)25);
                atribuirMemoria(25, (short)31);
                atribuirMemoria(26, (short)44);
                atribuirMemoria(27, (short)5);
                atribuirMemoria(28, (short)30);
                atribuirMemoria(29, (short)38);
                atribuirMemoria(30, (short)51);
                atribuirMemoria(31, (short)3);
                atribuirMemoria(35, (short)0);
                atribuirMemoria(36, (short)44);
                atribuirMemoria(37, (short)20);
                atribuirMemoria(38, (short)48);
                atribuirMemoria(39, (short)44);
                atribuirMemoria(40, (short)25);
                atribuirMemoria(41, (short)9);
                atribuirMemoria(42, (short)2);
                atribuirMemoria(43, (short)44);
                atribuirMemoria(44, (short)79);
                atribuirMemoria(45, (short)52);
                atribuirMemoria(46, (short)2);
                atribuirMemoria(47, (short)44);
                atribuirMemoria(48, (short)76);
                atribuirMemoria(49, (short)52);
                atribuirMemoria(50, (short)2);
                atribuirMemoria(51, (short)44);
                atribuirMemoria(52, (short)65);
                atribuirMemoria(53, (short)52);
                atribuirMemoria(54, (short)2);
                atribuirMemoria(55, (short)40);
                break;    
            case 12: //Exemplo Núcleo - OK!
                atribuirMemoria(0, (short)26);
                atribuirMemoria(1, (short)10);
                atribuirMemoria(2, (short)204);
                atribuirMemoria(3, (short)219);
                atribuirMemoria(4, (short)234);
                atribuirMemoria(5, (short)249);
                atribuirMemoria(6, (short)0);
                atribuirMemoria(10, (short)44);
                atribuirMemoria(11, (short)19);
                atribuirMemoria(12, (short)9);
                atribuirMemoria(13, (short)0);
                atribuirMemoria(14, (short)5);
                atribuirMemoria(15, (short)5);
                atribuirMemoria(16, (short)48);
                atribuirMemoria(17, (short)51);
                atribuirMemoria(19, (short)0);
                atribuirMemoria(20, (short)4);
                atribuirMemoria(21, (short)5);
                atribuirMemoria(22, (short)6);
                atribuirMemoria(23, (short)3);
                atribuirMemoria(24, (short)44);
                atribuirMemoria(25, (short)0);
                atribuirMemoria(26, (short)45);
                atribuirMemoria(27, (short)30);
                atribuirMemoria(28, (short)26);
                atribuirMemoria(29, (short)39);
                atribuirMemoria(30, (short)4);
                atribuirMemoria(31, (short)5);
                atribuirMemoria(32, (short)2);
                atribuirMemoria(33, (short)48);
                atribuirMemoria(34, (short)21);
                atribuirMemoria(35, (short)2);
                atribuirMemoria(36, (short)9);
                atribuirMemoria(37, (short)6);
                atribuirMemoria(38, (short)51);
                atribuirMemoria(39, (short)44);
                atribuirMemoria(40, (short)1);
                atribuirMemoria(41, (short)45);
                atribuirMemoria(42, (short)45);
                atribuirMemoria(43, (short)26);
                atribuirMemoria(44, (short)54);
                atribuirMemoria(45, (short)4);
                atribuirMemoria(46, (short)5);
                atribuirMemoria(47, (short)3);
                atribuirMemoria(48, (short)48);
                atribuirMemoria(49, (short)21);
                atribuirMemoria(50, (short)2);
                atribuirMemoria(51, (short)9);
                atribuirMemoria(52, (short)6);
                atribuirMemoria(53, (short)51);
                atribuirMemoria(54, (short)0);
                atribuirMemoria(55, (short)9);
                atribuirMemoria(56, (short)6);
                atribuirMemoria(57, (short)5);
                atribuirMemoria(58, (short)4);
                atribuirMemoria(59, (short)48);
                atribuirMemoria(60, (short)51);
                atribuirMemoria(70, (short)26);
                atribuirMemoria(71, (short)70);
                atribuirMemoria(74, (short)26);
                atribuirMemoria(75, (short)74);
                atribuirMemoria(78, (short)26);
                atribuirMemoria(79, (short)78);
                atribuirMemoria(205, (short)0);
                atribuirMemoria(206, (short)0);
                atribuirMemoria(207, (short)0);
                atribuirMemoria(208, (short)0);
                atribuirMemoria(209, (short)70);
                atribuirMemoria(220, (short)0);
                atribuirMemoria(221, (short)0);
                atribuirMemoria(222, (short)0);
                atribuirMemoria(223, (short)0);
                atribuirMemoria(224, (short)74);
                atribuirMemoria(235, (short)0);
                atribuirMemoria(236, (short)0);
                atribuirMemoria(237, (short)0);
                atribuirMemoria(238, (short)0);
                atribuirMemoria(239, (short)78);
                atribuirMemoria(250, (short)0);
                atribuirMemoria(251, (short)0);
                atribuirMemoria(252, (short)0);
                atribuirMemoria(253, (short)0);
                atribuirMemoria(254, (short)19);
                break;
//            case 1:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)3);
//                atribuirMemoria(3, (short)19);
//                atribuirMemoria(4, (short)9);
//                atribuirMemoria(5, (short)2);
//                atribuirMemoria(6, (short)40);
//                break;
//            case 2:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)19);
//                atribuirMemoria(2, (short)19);
//                atribuirMemoria(3, (short)19);
//                atribuirMemoria(4, (short)19);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)40);
//                break;
//            case 3:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)3);
//                atribuirMemoria(2, (short)29);
//                atribuirMemoria(3, (short)20);
//                atribuirMemoria(4, (short)20);
//                atribuirMemoria(5, (short)20);
//                atribuirMemoria(6, (short)22);
//                atribuirMemoria(7, (short)25);
//                atribuirMemoria(8, (short)11);
//                atribuirMemoria(9, (short)26);
//                atribuirMemoria(10, (short)3);
//                atribuirMemoria(11, (short)40);
//                break;
//            case 4:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)19);
//                atribuirMemoria(2, (short)19);
//                atribuirMemoria(3, (short)9);
//                atribuirMemoria(4, (short)15);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)19);
//                atribuirMemoria(7, (short)3);
//                atribuirMemoria(8, (short)5);
//                atribuirMemoria(9, (short)15);
//                atribuirMemoria(10, (short)40);
//                break;
//            case 5:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)50);
//                atribuirMemoria(3, (short)48);
//                atribuirMemoria(4, (short)0);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)31);
//                atribuirMemoria(7, (short)37);
//                atribuirMemoria(8, (short)40);
//                break;
//            case 6:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)3);
//                atribuirMemoria(2, (short)4);
//                atribuirMemoria(3, (short)44);
//                atribuirMemoria(4, (short)23);
//                atribuirMemoria(5, (short)3);
//                atribuirMemoria(6, (short)44);
//                atribuirMemoria(7, (short)1);
//                atribuirMemoria(8, (short)10);
//                atribuirMemoria(9, (short)0);
//                atribuirMemoria(10, (short)19);
//                atribuirMemoria(11, (short)10);
//                atribuirMemoria(12, (short)1);
//                atribuirMemoria(13, (short)19);
//                atribuirMemoria(14, (short)10);
//                atribuirMemoria(15, (short)2);
//                atribuirMemoria(16, (short)6);
//                atribuirMemoria(17, (short)0);
//                atribuirMemoria(18, (short)4);
//                atribuirMemoria(19, (short)6);
//                atribuirMemoria(20, (short)1);
//                atribuirMemoria(21, (short)40);
//                break;
//            case 7:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)1024);
//                atribuirMemoria(3, (short)48);
//                atribuirMemoria(4, (short)27);
//                atribuirMemoria(5, (short)6);
//                atribuirMemoria(6, (short)27);
//                atribuirMemoria(7, (short)30);
//                atribuirMemoria(8, (short)30);
//                atribuirMemoria(9, (short)40);
//                atribuirMemoria(30, (short)31);
//                atribuirMemoria(31, (short)5);
//                atribuirMemoria(32, (short)1024);
//                atribuirMemoria(33, (short)3);
//                atribuirMemoria(34, (short)30);
//                atribuirMemoria(35, (short)38);
//                atribuirMemoria(36, (short)28);
//                break;
//            case 8://ex 1.1 e 2.1
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)19);
//                atribuirMemoria(2, (short)19);
//                atribuirMemoria(3, (short)40);
//                break;
//            case 9://ex 1.2
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)3);
//                atribuirMemoria(3, (short)19);
//                atribuirMemoria(4, (short)9);
//                atribuirMemoria(5, (short)2);
//                atribuirMemoria(6, (short)40);
//                break;
//            case 10://ex 1.3
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)3);
//                atribuirMemoria(2, (short)29);
//                atribuirMemoria(3, (short)20);
//                atribuirMemoria(4, (short)20);
//                atribuirMemoria(5, (short)22);
//                atribuirMemoria(6, (short)25);
//                atribuirMemoria(7, (short)10);
//                atribuirMemoria(8, (short)26);
//                atribuirMemoria(9, (short)3);
//                atribuirMemoria(10, (short)40);
//                break;
//            case 11://ex 1.4
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)19);
//                atribuirMemoria(2, (short)19);
//                atribuirMemoria(3, (short)9);
//                atribuirMemoria(4, (short)15);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)19);
//                atribuirMemoria(7, (short)3);
//                atribuirMemoria(8, (short)5);
//                atribuirMemoria(9, (short)15);
//                atribuirMemoria(10, (short)40);
//                break;
//            case 12://ex 1.5
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)50);
//                atribuirMemoria(3, (short)48);
//                atribuirMemoria(4, (short)0);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)31);
//                atribuirMemoria(7, (short)37);
//                atribuirMemoria(8, (short)40);
//                break;
//            case 13://ex 1.6
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)3);
//                atribuirMemoria(2, (short)4);
//                atribuirMemoria(3, (short)44);
//                atribuirMemoria(4, (short)30);
//                atribuirMemoria(5, (short)3);
//                atribuirMemoria(6, (short)44);
//                atribuirMemoria(7, (short)1);
//                atribuirMemoria(8, (short)10);
//                atribuirMemoria(9, (short)0);
//                atribuirMemoria(10, (short)19);
//                atribuirMemoria(11, (short)10);
//                atribuirMemoria(12, (short)1);
//                atribuirMemoria(13, (short)19);
//                atribuirMemoria(14, (short)10);
//                atribuirMemoria(15, (short)2);
//                atribuirMemoria(16, (short)6);
//                atribuirMemoria(17, (short)0);
//                atribuirMemoria(18, (short)4);
//                atribuirMemoria(19, (short)6);
//                atribuirMemoria(20, (short)1);
//                atribuirMemoria(21, (short)40);
//                break;
//            case 14://ex 2.3
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)4);
//                atribuirMemoria(3, (short)25);
//                atribuirMemoria(4, (short)8);
//                atribuirMemoria(5, (short)22);
//                atribuirMemoria(6, (short)26);
//                atribuirMemoria(7, (short)3);
//                atribuirMemoria(8, (short)40);
//                break;
//            case 15://ex 2.4
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)16);
//                atribuirMemoria(10, (short)0);
//                atribuirMemoria(11, (short)9);
//                atribuirMemoria(12, (short)2);
//                atribuirMemoria(13, (short)9);
//                atribuirMemoria(14, (short)3);
//                atribuirMemoria(15, (short)28);
//                atribuirMemoria(16, (short)0);
//                atribuirMemoria(17, (short)44);
//                atribuirMemoria(18, (short)9);
//                atribuirMemoria(19, (short)48);
//                atribuirMemoria(20, (short)27);
//                atribuirMemoria(21, (short)10);
//                atribuirMemoria(22, (short)40);
//                break;
//            case 16://ex 2.6
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)16);
//                atribuirMemoria(10, (short)19);
//                atribuirMemoria(11, (short)9);
//                atribuirMemoria(12, (short)2);
//                atribuirMemoria(13, (short)9);
//                atribuirMemoria(14, (short)3);
//                atribuirMemoria(15, (short)28);
//                atribuirMemoria(16, (short)0);
//                atribuirMemoria(17, (short)44);
//                atribuirMemoria(18, (short)9);
//                atribuirMemoria(19, (short)48);
//                atribuirMemoria(20, (short)27);
//                atribuirMemoria(21, (short)10);
//                atribuirMemoria(22, (short)40);
//                break;
//
//            case 17: //ex3.1
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)20);
//                atribuirMemoria(20, (short)0);
//                atribuirMemoria(21, (short)44);
//                atribuirMemoria(22, (short)14);
//                atribuirMemoria(23, (short)48);
//                atribuirMemoria(24, (short)9);
//                atribuirMemoria(25, (short)3);
//                atribuirMemoria(26, (short)27);
//                atribuirMemoria(27, (short)50);
//                atribuirMemoria(28, (short)1);
//                atribuirMemoria(29, (short)9);
//                atribuirMemoria(30, (short)4);
//                atribuirMemoria(31, (short)2);
//                atribuirMemoria(32, (short)9);
//                atribuirMemoria(33, (short)5);
//                atribuirMemoria(34, (short)40);
//                //até aqui é igual
//                atribuirMemoria(50, (short)0);
//                atribuirMemoria(51, (short)44);
//                atribuirMemoria(52, (short)3);
//                atribuirMemoria(53, (short)31);
//                atribuirMemoria(54, (short)22);
//                atribuirMemoria(55, (short)31);
//                atribuirMemoria(56, (short)37);
//                atribuirMemoria(57, (short)36);
//                atribuirMemoria(58, (short)28);
//                break;
//            case 18: //ex3.2
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)20);
//                atribuirMemoria(20, (short)0);
//                atribuirMemoria(21, (short)44);
//                atribuirMemoria(22, (short)14);
//                atribuirMemoria(23, (short)48);
//                atribuirMemoria(24, (short)9);
//                atribuirMemoria(25, (short)3);
//                atribuirMemoria(26, (short)27);
//                atribuirMemoria(27, (short)50);
//                atribuirMemoria(28, (short)1);
//                atribuirMemoria(29, (short)9);
//                atribuirMemoria(30, (short)4);
//                atribuirMemoria(31, (short)2);
//                atribuirMemoria(32, (short)9);
//                atribuirMemoria(33, (short)5);
//                atribuirMemoria(34, (short)40);
//                //até aqui é igual
//                atribuirMemoria(50, (short)0);
//                atribuirMemoria(51, (short)44);
//                atribuirMemoria(52, (short)28);
//                atribuirMemoria(53, (short)31);
//                atribuirMemoria(54, (short)44);
//                atribuirMemoria(55, (short)3);
//                atribuirMemoria(56, (short)31);
//                atribuirMemoria(57, (short)22);
//                atribuirMemoria(58, (short)31);
//                atribuirMemoria(59, (short)37);
//                atribuirMemoria(60, (short)36);
//                atribuirMemoria(61, (short)28);
//                break;
//            case 19: //ex3.3
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)20);
//                atribuirMemoria(20, (short)0);
//                atribuirMemoria(21, (short)44);
//                atribuirMemoria(22, (short)14);
//                atribuirMemoria(23, (short)48);
//                atribuirMemoria(24, (short)9);
//                atribuirMemoria(25, (short)3);
//                atribuirMemoria(26, (short)27);
//                atribuirMemoria(27, (short)50);
//                atribuirMemoria(28, (short)1);
//                atribuirMemoria(29, (short)9);
//                atribuirMemoria(30, (short)4);
//                atribuirMemoria(31, (short)2);
//                atribuirMemoria(32, (short)9);
//                atribuirMemoria(33, (short)5);
//                atribuirMemoria(34, (short)27);
//                atribuirMemoria(35, (short)10);
//                atribuirMemoria(36, (short)27);
//                atribuirMemoria(37, (short)10);
//                atribuirMemoria(38, (short)40);
//                //até aqui é igual
//                atribuirMemoria(50, (short)0);
//                atribuirMemoria(51, (short)44);
//                atribuirMemoria(52, (short)28);
//                atribuirMemoria(53, (short)31);
//                atribuirMemoria(54, (short)44);
//                atribuirMemoria(55, (short)3);
//                atribuirMemoria(56, (short)31);
//                atribuirMemoria(57, (short)22);
//                atribuirMemoria(58, (short)31);
//                atribuirMemoria(59, (short)37);
//                atribuirMemoria(60, (short)36);
//                atribuirMemoria(61, (short)28);         
//                break;
//            case 20:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)44);
//                atribuirMemoria(2, (short)255);
//                atribuirMemoria(3, (short)48);
//                atribuirMemoria(4, (short)27);
//                atribuirMemoria(5, (short)10);
//                atribuirMemoria(6, (short)27);
//                atribuirMemoria(7, (short)10);
//                atribuirMemoria(8, (short)30);
//                atribuirMemoria(9, (short)40);
//                atribuirMemoria(10, (short)31);
//                atribuirMemoria(11, (short)5);
//                atribuirMemoria(12, (short)255);
//                atribuirMemoria(13, (short)3);
//                atribuirMemoria(14, (short)30);
//                atribuirMemoria(15, (short)38);
//                atribuirMemoria(16, (short)28);            
//                break;
//            case 21:
//                atribuirMemoria(0, (short)0);
//                atribuirMemoria(1, (short)39);
//                atribuirMemoria(2, (short)39);
//                atribuirMemoria(3, (short)39);
//                atribuirMemoria(4, (short)39);
//                atribuirMemoria(5, (short)39);
//                atribuirMemoria(6, (short)39);
//                atribuirMemoria(7, (short)39);
//                atribuirMemoria(8, (short)44);
//                atribuirMemoria(9, (short)31);
//                atribuirMemoria(10, (short)9);
//                atribuirMemoria(11, (short)1);
//                atribuirMemoria(12, (short)44);
//                atribuirMemoria(13, (short)27);
//                atribuirMemoria(14, (short)9);
//                atribuirMemoria(15, (short)2);
//                atribuirMemoria(16, (short)44);
//                atribuirMemoria(17, (short)255);
//                atribuirMemoria(18, (short)48);
//                atribuirMemoria(19, (short)30);
//                atribuirMemoria(20, (short)52);
//                atribuirMemoria(21, (short)1);
//                atribuirMemoria(22, (short)30);
//                atribuirMemoria(23, (short)52);
//                atribuirMemoria(24, (short)2);
//                atribuirMemoria(25, (short)30);
//                atribuirMemoria(26, (short)40);
//                atribuirMemoria(27, (short)0);
//                atribuirMemoria(28, (short)44);
//                atribuirMemoria(29, (short)200);
//                atribuirMemoria(30, (short)30);
//                atribuirMemoria(31, (short)51);
//                break;
//            case 22: //prova 1
//                atribuirMemoria(0, (short)44);
//                atribuirMemoria(1, (short)4);
//                atribuirMemoria(2, (short)3);
//                atribuirMemoria(3, (short)44);
//                atribuirMemoria(4, (short)1);
//                atribuirMemoria(5, (short)19);
//                atribuirMemoria(6, (short)19);
//                atribuirMemoria(7, (short)53);
//                atribuirMemoria(8, (short)1);
//                atribuirMemoria(9, (short)25);
//                atribuirMemoria(10, (short)17);
//                atribuirMemoria(11, (short)44);
//                atribuirMemoria(12, (short)3);
//                atribuirMemoria(13, (short)9);
//                atribuirMemoria(14, (short)1);
//                atribuirMemoria(15, (short)26);
//                atribuirMemoria(16, (short)0);
//                atribuirMemoria(17, (short)40);
//                break;
//            case 23: //exercício PIC
//                atribuirMemoria(0, (short)44);
//                atribuirMemoria(1, (short)216);
//                atribuirMemoria(2, (short)9);
//                atribuirMemoria(3, (short)35);
//                atribuirMemoria(4, (short)44);
//                atribuirMemoria(5, (short)226);
//                atribuirMemoria(6, (short)9);
//                atribuirMemoria(7, (short)36);
//                atribuirMemoria(8, (short)44);
//                atribuirMemoria(9, (short)236);
//                atribuirMemoria(10, (short)9);
//                atribuirMemoria(11, (short)37);
//                atribuirMemoria(12, (short)44);
//                atribuirMemoria(13, (short)246);
//                atribuirMemoria(14, (short)9);
//                atribuirMemoria(15, (short)38);
//                atribuirMemoria(16, (short)44);
//                atribuirMemoria(17, (short)200);
//                atribuirMemoria(18, (short)9);
//                atribuirMemoria(19, (short)43);
//                atribuirMemoria(20, (short)44);
//                atribuirMemoria(21, (short)202);
//                atribuirMemoria(22, (short)9);
//                atribuirMemoria(23, (short)45);
//                atribuirMemoria(24, (short)44);
//                atribuirMemoria(25, (short)204);
//                atribuirMemoria(26, (short)9);
//                atribuirMemoria(27, (short)47);
//                atribuirMemoria(28, (short)44);
//                atribuirMemoria(29, (short)135);
//                atribuirMemoria(30, (short)9);
//                atribuirMemoria(31, (short)49);
//                atribuirMemoria(32, (short)26);
//                atribuirMemoria(33, (short)50);
//                atribuirMemoria(34, (short)0);
//                atribuirMemoria(35, (short)44);
//                atribuirMemoria(36, (short)200);
//                atribuirMemoria(37, (short)9);
//                atribuirMemoria(38, (short)0);
//                atribuirMemoria(39, (short)44);
//                atribuirMemoria(40, (short)202);
//                atribuirMemoria(41, (short)9);
//                atribuirMemoria(42, (short)1);
//                atribuirMemoria(43, (short)44);
//                atribuirMemoria(44, (short)204);
//                atribuirMemoria(45, (short)9);
//                atribuirMemoria(46, (short)2);
//                atribuirMemoria(47, (short)44);
//                atribuirMemoria(48, (short)150);
//                atribuirMemoria(49, (short)9);
//                atribuirMemoria(50, (short)3);
//                atribuirMemoria(51, (short)5);
//                atribuirMemoria(52, (short)38);
//                atribuirMemoria(53, (short)48);
//                atribuirMemoria(54, (short)5);
//                atribuirMemoria(55, (short)35);
//                atribuirMemoria(56, (short)48);
//                atribuirMemoria(57, (short)11);
//                atribuirMemoria(58, (short)5);
//                atribuirMemoria(59, (short)0);
//                atribuirMemoria(60, (short)31);
//                atribuirMemoria(61, (short)0);
//                atribuirMemoria(62, (short)31);
//                atribuirMemoria(63, (short)31);
//                atribuirMemoria(64, (short)32);
//                atribuirMemoria(65, (short)33);
//                atribuirMemoria(66, (short)47);
//                atribuirMemoria(67, (short)9);
//                atribuirMemoria(68, (short)35);
//                atribuirMemoria(69, (short)5);
//                atribuirMemoria(70, (short)36);
//                atribuirMemoria(71, (short)48);
//                atribuirMemoria(72, (short)11);
//                atribuirMemoria(73, (short)5);
//                atribuirMemoria(74, (short)1);
//                atribuirMemoria(75, (short)31);
//                atribuirMemoria(76, (short)0);
//                atribuirMemoria(77, (short)31);
//                atribuirMemoria(78, (short)31);
//                atribuirMemoria(79, (short)32);
//                atribuirMemoria(80, (short)33);
//                atribuirMemoria(81, (short)47);
//                atribuirMemoria(82, (short)9);
//                atribuirMemoria(83, (short)36);
//                atribuirMemoria(84, (short)5);
//                atribuirMemoria(85, (short)37);
//                atribuirMemoria(86, (short)48);
//                atribuirMemoria(87, (short)11);
//                atribuirMemoria(88, (short)5);
//                atribuirMemoria(89, (short)2);
//                atribuirMemoria(90, (short)31);
//                atribuirMemoria(91, (short)0);
//                atribuirMemoria(92, (short)31);
//                atribuirMemoria(93, (short)31);
//                atribuirMemoria(94, (short)32);
//                atribuirMemoria(95, (short)33);
//                atribuirMemoria(96, (short)47);
//                atribuirMemoria(97, (short)9);
//                atribuirMemoria(98, (short)37);
//                atribuirMemoria(99, (short)5);
//                atribuirMemoria(100, (short)38);
//                atribuirMemoria(101, (short)48);
//                atribuirMemoria(102, (short)0);
//                atribuirMemoria(103, (short)9);
//                atribuirMemoria(104, (short)39);
//                atribuirMemoria(105, (short)52);
//                atribuirMemoria(106, (short)5);
//                atribuirMemoria(107, (short)52);
//                atribuirMemoria(108, (short)6);
//                atribuirMemoria(109, (short)52);
//                atribuirMemoria(110, (short)7);
//                atribuirMemoria(111, (short)52);
//                atribuirMemoria(112, (short)3);
//                atribuirMemoria(113, (short)40);
//                atribuirMemoria(114, (short)5);
//                atribuirMemoria(115, (short)39);
//                atribuirMemoria(116, (short)3);
//                atribuirMemoria(117, (short)44);
//                atribuirMemoria(118, (short)0);
//                atribuirMemoria(119, (short)45);
//                atribuirMemoria(120, (short)159);
//                atribuirMemoria(121, (short)26);
//                atribuirMemoria(122, (short)168);
//                atribuirMemoria(123, (short)4);
//                atribuirMemoria(124, (short)5);
//                atribuirMemoria(125, (short)36);
//                atribuirMemoria(126, (short)48);
//                atribuirMemoria(127, (short)36);
//                atribuirMemoria(128, (short)21);
//                atribuirMemoria(129, (short)2);
//                atribuirMemoria(130, (short)9);
//                atribuirMemoria(131, (short)39);
//                atribuirMemoria(132, (short)51);
//                atribuirMemoria(133, (short)44);
//                atribuirMemoria(134, (short)1);
//                atribuirMemoria(135, (short)45);
//                atribuirMemoria(136, (short)176);
//                atribuirMemoria(137, (short)26);
//                atribuirMemoria(138, (short)186);
//                atribuirMemoria(139, (short)2);
//                atribuirMemoria(140, (short)5);
//                atribuirMemoria(141, (short)37);
//                atribuirMemoria(142, (short)48);
//                atribuirMemoria(143, (short)21);
//                atribuirMemoria(144, (short)2);
//                atribuirMemoria(145, (short)9);
//                atribuirMemoria(146, (short)39);
//                atribuirMemoria(147, (short)51);
//                atribuirMemoria(148, (short)5);
//                atribuirMemoria(149, (short)35);
//                atribuirMemoria(150, (short)48);
//                atribuirMemoria(151, (short)0);
//                atribuirMemoria(152, (short)9);
//                atribuirMemoria(153, (short)39);
//                atribuirMemoria(154, (short)51);
//                atribuirMemoria(155, (short)26);
//                atribuirMemoria(156, (short)200);
//                atribuirMemoria(157, (short)26);
//                atribuirMemoria(158, (short)202);
//                atribuirMemoria(159, (short)26);
//                atribuirMemoria(160, (short)204);
//                break;
//            case 24: //Nucleo de SO
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)10);
//                atribuirMemoria(2, (short)204);
//                atribuirMemoria(3, (short)219);
//                atribuirMemoria(4, (short)234);
//                atribuirMemoria(5, (short)249);
//                atribuirMemoria(10, (short)44);	
//                atribuirMemoria(11, (short)19);
//                atribuirMemoria(12, (short)9);
//                atribuirMemoria(13, (short)0);
//                atribuirMemoria(14, (short)5);
//                atribuirMemoria(15, (short)5);
//                atribuirMemoria(16, (short)48);
//                atribuirMemoria(17, (short)39);
//                atribuirMemoria(18, (short)51);	
//                atribuirMemoria(19, (short)0);	
//                atribuirMemoria(20, (short)4);
//                atribuirMemoria(21, (short)5);
//                atribuirMemoria(22, (short)6);
//                atribuirMemoria(23, (short)3);
//                atribuirMemoria(24, (short)44);
//                atribuirMemoria(25, (short)0);
//                atribuirMemoria(26, (short)45);
//                atribuirMemoria(27, (short)30);
//                atribuirMemoria(28, (short)26);
//                atribuirMemoria(29, (short)39);
//                atribuirMemoria(30, (short)4);
//                atribuirMemoria(31, (short)5);
//                atribuirMemoria(32, (short)2);
//                atribuirMemoria(33, (short)48);
//                atribuirMemoria(34, (short)21);
//                atribuirMemoria(35, (short)2);
//                atribuirMemoria(36, (short)9);
//                atribuirMemoria(37, (short)6);
//                atribuirMemoria(38, (short)51);
//                atribuirMemoria(39, (short)44);
//                atribuirMemoria(40, (short)1);
//                atribuirMemoria(41, (short)45);
//                atribuirMemoria(42, (short)45);
//                atribuirMemoria(43, (short)26);
//                atribuirMemoria(44, (short)54);
//                atribuirMemoria(45, (short)4);
//                atribuirMemoria(46, (short)5);
//                atribuirMemoria(47, (short)3);
//                atribuirMemoria(48, (short)48);
//                atribuirMemoria(49, (short)21);
//                atribuirMemoria(50, (short)2);	
//                atribuirMemoria(51, (short)9);	
//                atribuirMemoria(52, (short)6);	
//                atribuirMemoria(53, (short)51);	
//                atribuirMemoria(54, (short)0);	
//                atribuirMemoria(55, (short)9);	
//                atribuirMemoria(56, (short)6);	
//                atribuirMemoria(57, (short)5);	
//                atribuirMemoria(58, (short)4);
//                atribuirMemoria(59, (short)48);
//                atribuirMemoria(60, (short)51);	                
//                atribuirMemoria(70, (short)26);	  
//                atribuirMemoria(71, (short)70);
//                atribuirMemoria(74, (short)26);	  
//                atribuirMemoria(75, (short)74);	  	  
//                atribuirMemoria(78, (short)26);	  
//                atribuirMemoria(79, (short)78);
//                atribuirMemoria(209, (short)70);
//                atribuirMemoria(224, (short)74);
//                atribuirMemoria(239, (short)78);
//                atribuirMemoria(254, (short)19);
//                break;
//            case 25:
//                atribuirMemoria(0, (short)26);
//                atribuirMemoria(1, (short)2);
//                atribuirMemoria(2, (short)40);
//                break;                
            default:
                programa = 0;
                break;
        }
        MVM.decodificador(mem, programa, 0);
        SalvarPrograma.salvar(enderecoDeCarga, lastPosition, mem);
    }
    
    private void atribuirMemoria(int posicao, short valor){
        mem[posicao + enderecoDeCarga] = valor;
        if(posicao+enderecoDeCarga > lastPosition) lastPosition = posicao+enderecoDeCarga;
    }
}
